version: '3.3'
services:
  balarcade-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'balarcade'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "C:/Progetti/docker_mysql:/var/lib/mysql"
volumes:
  mysql-db: